backend:
  name: git-gateway

media_folder: "site/static/img/" # Folder where user uploaded files should go
public_folder: "/img"

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
        - label: "Home"
          name: "Home"
          file: "site/content/_index.md"
          fields:
              - {label: "Hero", name: "hero", widget: object, required: false, fields: [
                  {label: "Title", name: "title", widget: string, required: false},
                  {label: "Logo", name: "logo", widget: image, required: false},
                  {label: "Image", name: "img", widget: image, required: false},
              ]}
              - {label: "Delivery", name: "delivery2", widget: object, required: false, fields: [
                  {label: "Title", name: "title", widget: string, required: false},
                  {label: "Empresas", name: "empresas", widget: list, allow_add: true, required: false, fields: [
                    {label: "Image", name: "img", widget: image, required: false},
                    {label: "Link", name: "url", widget: string, required: false},
                  ]}
                ]}
              - {label: "Conceito", name: "conceito", widget: object, required: false, fields: [
                  {label: "Image", name: "img", widget: image, required: false},
                  {label: "Title", name: "title", widget: string, required: false},
                  {label: "Dica", name: "dica", widget: string, required: false},
                  {label: "Texto", name: "content", widget: text, required: false},
              ]}
              - {label: "Receita", name: "receita", widget: list, allow_add: true, required: false, fields: [
                  {label: "Nome", name: "name", widget: string, required: false},
                  {label: "Descrição", name: "description", widget: string, required: false},
              ]}
              - {label: "Cardapio", name: "cardapio", widget: list, allow_add: true, required: false, fields: [
                  {label: "Nome", name: "name", widget: text, required: false},
                  {label: "Borda", name: "border", widget: boolean, required: false},
                  {label: "Preço", name: "price", widget: number, required: false},
                  {label: "Description", name: "description", widget: string, required: false},
                  {label: "Extra", name: "extra", widget: string, required: false},
                  {label: "Titulo (só coloque se for título)", name: "title", widget: string, required: false},
              ]}
              - {label: "Delivery", name: "delivery", widget: object, required: false, fields: [
                  {label: "Title", name: "title", widget: string, required: false},
                  {label: "Empresas", name: "empresas", widget: list, allow_add: true, required: false, fields: [
                    {label: "Image", name: "img", widget: image, required: false},
                    {label: "Link", name: "url", widget: string, required: false},
                  ]}
                ]}
              - {label: "Contato", name: "contato", widget: object, required: false, fields: [
                  {label: "Título", name: "title", widget: string, required: false},
                  {label: "Descrição", name: "description", widget: text, required: false},
                  {label: "Mídias sociais", name: "medias", widget: list, allow_add: true, required: false, fields: [
                      {label: "Image", name: "img", widget: image, required: false},
                      {label: "Link", name: "url", widget: string, required: false}]},
                  {label: "Fotos", name: "background", widget: list, allow_add: false, required: false, fields: [
                      {label: "Image", name: "img", widget: image, required: true}]}
              ]}
              - {label: "Localização", name: "localizacao", widget: list, allow_add: true, required: false, fields: [
                  {label: "Endereço", name: "endereco", widget: string, required: false},
                  {label: "Telefone", name: "telefone", widget: string, required: false},
                  {label: "Horário", name: "horario", widget: text, required: false},
              ]}
              - {label: "Footer", name: "feet", widget: object, required: false, fields: [
                  {label: "Logo", name: "logo", widget: image, required: false},
                  {label: "Texto", name: "text", widget: string, required: false},
              ]}
